version: '3'

services: #Apache Proxy Container
  apache-proxy:
    image: imagediouxx/apache-proxy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-proxy
    hostname: apache-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /etc/ssl/:/opt/ssl
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  nginx-teste:
    container_name: 'nginx-teste'
    image: 'nginx:latest'
    ports:
      - '8080:80'
    volumes:
      - ./html:/usr/share/nginx/html